export const icons = {
  github: 'i-lucide-github',
  star: 'i-lucide-star',
  fork: 'i-lucide-git-fork',
  license: 'i-lucide-scale',
  code: 'i-lucide-code',
  construction: 'i-lucide-construction',
  clock: 'i-lucide-clock-alert',
  zoomIn: 'i-lucide-zoom-in',
  zoomOut: 'i-lucide-zoom-out',
  reset: 'i-lucide-scan',
  copy: 'i-lucide-copy',
  check: 'i-lucide-check',
  monitor: 'i-lucide-monitor',
  sun: 'i-lucide-sun',
  moon: 'i-lucide-moon',
  notebook: 'i-lucide-notebook-pen',
  layers: 'i-lucide-layers-2',
  shapes: 'i-lucide-shapes',
  user: 'i-lucide-user-round',
  search: 'i-lucide-search',
  rss: 'i-lucide-rss',
  command: 'i-lucide-command',
  menu: 'i-lucide-menu',
  close: 'i-lucide-x',
  home: 'i-lucide-house',
  left: 'i-lucide-arrow-left',
  up: 'i-lucide-arrow-up',
  arrow: 'i-lucide-arrow-up-right',
  chevron: 'i-lucide-chevron-right',
  pen: 'i-lucide-pen-line',
  image: 'i-lucide-image',
  languages: 'i-lucide-languages',
  folder: 'i-lucide-folder-open',
  tags: 'i-lucide-tags',
  eye: 'i-lucide-eye',
  users: 'i-lucide-users-round',
  terminal: 'i-lucide-terminal',
  list: 'i-lucide-list',
  grid: 'i-lucide-layout-grid',
  pin: 'i-lucide-pin',
  down: 'i-lucide-chevron-down',
  toc: 'i-lucide-list-tree',
} as const

export type IconName = keyof typeof icons
