import { defineConfig, presetIcons, presetWind3 } from 'unocss'
import { icons } from './app/shared/icons.ts'

const breakpoints = { md: '900px', lg: '1200px' }

export default defineConfig({
  presets: [presetWind3(), presetIcons({ scale: 1.1 })],
  theme: {
    breakpoints,
    colors: {
      'canvas': 'var(--color-canvas)',
      'surface': 'var(--color-surface)',
      'ink': 'var(--color-text)',
      'heading': 'var(--color-heading)',
      'muted': 'var(--color-muted)',
      'accent': 'var(--color-accent)',
      'accent-surface': 'var(--color-accent-surface)',
      'accent-soft': 'var(--color-accent-text)',
      'themed': 'var(--color-title)',
      'on-accent': 'var(--color-on-accent)',
      'accent-hover': 'var(--color-accent-hover)',
      'accent-pressed': 'var(--color-accent-pressed)',
      'accent-pressed-solid': 'var(--color-accent-pressed-solid)',
      'code': 'var(--color-code)',
      'line': 'var(--color-border)',
      'line-strong': 'var(--color-border-strong)',
      'info': 'var(--color-info)',
      'success': 'var(--color-success)',
      'warn': 'var(--color-warn)',
      'error': 'var(--color-error)',
      'acrylic': 'var(--color-acrylic)',
      'scrim': 'var(--color-scrim)',
    },
    fontFamily: {
      sans: 'var(--font-sans)',
      mono: 'var(--font-mono)',
      display: 'var(--font-display)',
    },
    fontSize: {
      'xxxxl': ['var(--text-xxxxl)', '1.25'],
      'xxxl': ['var(--text-xxxl)', '1.25'],
      'xxl': ['var(--text-xxl)', '1.4'],
      'xl': ['var(--text-xl)', '1.5'],
      'l': ['var(--text-l)', '1.65'],
      'm': ['var(--text-m)', '1.8'],
      's': ['var(--text-s)', '1.65'],
      'xs': ['var(--text-xs)', '1.65'],
      'xxs': ['var(--text-xxs)', '1.65'],
      'xxxs': ['var(--text-xxxs)', '1.65'],
      'base': ['var(--text-s)', '1.65'],
      'sm': ['var(--text-xs)', '1.65'],
      'page': ['var(--text-xxxl)', '1.25'],
      'section': ['var(--text-xxl)', '1.4'],
      'title': ['var(--text-l)', '1.65'],
      'error-title': ['var(--text-xl)', '1.65'],
    },
    borderRadius: {
      panel: 'var(--radius-panel)',
      button: 'var(--radius-button)',
      chip: 'var(--radius-chip)',
    },
    boxShadow: {
      floating: 'var(--shadow-float)',
      dialog: 'var(--shadow-dialog)',
    },
    maxWidth: { site: 'var(--layout-width)' },
    spacing: {
      layout: 'var(--layout-gap)',
    },
    zIndex: {
      header: 'var(--z-header)',
      actions: 'var(--z-actions)',
    },
  },
  extendTheme: theme => ({ ...theme, breakpoints }),
  shortcuts: {
    'ui-feedback': '[transition-property:color,background-color,border-color,text-decoration-color,box-shadow,opacity] duration-[var(--duration-interaction)] ease-[var(--ease-interaction)] motion-reduce:transition-none',
    'control-disabled': 'disabled:pointer-events-none disabled:opacity-45 aria-disabled:pointer-events-none aria-disabled:opacity-45 data-[disabled]:pointer-events-none data-[disabled]:opacity-45',
    'control-base': 'ui-feedback control-disabled min-h-11 inline-flex items-center justify-center gap-2 rounded-button',
    'control-quiet': 'ui-feedback control-disabled rounded-button hover:bg-accent-surface hover:text-accent-soft active:bg-accent-pressed',
    'control-selected': 'bg-accent-surface text-accent-soft',
    'button-primary': 'control-base border border-transparent bg-accent px-[17px] py-[9px] text-base text-on-accent font-semibold hover:bg-accent-hover active:bg-accent-pressed-solid',
    'ui-link': 'ui-feedback underline-offset-4 hover:text-accent-soft hover:underline hover:decoration-current active:text-accent-soft',
    'field-control': 'ui-feedback control-disabled min-h-11 min-w-0 border border-line-strong rounded-button bg-canvas text-ink hover:border-accent focus-visible:border-accent',
    'card-link': 'ui-feedback hover:border-accent focus-visible:border-accent active:border-accent',
    'chip-link': 'ui-feedback max-w-full min-h-11 inline-flex items-center gap-1.5 break-words border rounded-chip px-2.5 text-sm md:min-h-8 hover:border-accent hover:bg-accent-surface hover:text-accent-soft active:bg-accent-pressed',
    'cover-field': 'flex min-w-0 flex-col gap-2 text-xs text-muted',
    'cover-input': 'field-control w-full px-3 text-sm',
    'site-container': 'mx-auto w-full max-w-site px-5 md:px-8',
    'section-label': 'text-base tracking-widest text-muted font-medium',
    'icon-button':
      'control-base control-quiet h-11 w-11 shrink-0 text-muted',
    'text-link': 'ui-link inline-flex items-center gap-2 min-h-11 text-heading',
  },
  safelist: Object.values(icons),
})
